controller_list:
#  - name: /sdk/robot/limb/left
  - name: /baxter/right_arm_joint_position_controller
    ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - right_s0
      - right_s1
      - right_e0
      - right_e1
      - right_w0
      - right_w1
      - right_w2
