controller_list:
#  - name: /sdk/robot/limb/left
  - name: /baxter/left_arm_joint_position_controller
    ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - left_s0
      - left_s1
      - left_e0
      - left_e1
      - left_w0
      - left_w1
      - left_w2
