baxter:
  right_arm_joint_position_controller:
    type: reflexxes_effort_controllers/JointTrajectoryController
    sampling_resolution: 0.001
    joint_names: 
      - 'right_s0'
      - 'right_s1'
      - 'right_e0'
      - 'right_e1'
      - 'right_w0'
      - 'right_w1'
      - 'right_w2'
    joints:
      right_s0:
        pid: {p: 5.0, i: 1.0, d: 1.0}
        position_tolerance: 0.1
        max_acceleration: 0.5
      right_s1:
        pid: {p: 5.0, i: 1.0, d: 1.0}
        position_tolerance: 0.1
        max_acceleration: 0.5
      right_e0:
        pid: {p: 5.0, i: 1.0, d: 1.0}
        position_tolerance: 0.1
        max_acceleration: 0.5
      right_e1:
        pid: {p: 5.0, i: 1.0, d: 1.0}
        position_tolerance: 0.1
        max_acceleration: 0.5
      right_w0:
        pid: {p: 5.0, i: 1.0, d: 1.0}
        position_tolerance: 0.1
        max_acceleration: 0.5
      right_w1:
        pid: {p: 5.0, i: 1.0, d: 1.0}
        position_tolerance: 0.1
        max_acceleration: 0.5
      right_w2:
        pid: {p: 10.0, i: 0.0, d: 0.0}
        position_tolerance: 0.1
        max_acceleration: 0.5      
  left_arm_joint_position_controller:
    type: reflexxes_effort_controllers/JointTrajectoryController
    sampling_resolution: 0.001
    joint_names: 
      - 'left_s0'
      - 'left_s1'
      - 'left_e0'
      - 'left_e1'
      - 'left_w0'
      - 'left_w1'
      - 'left_w2'
    joints:
      left_s0:
        pid: {p: 5.0, i: 1.0, d: 1.0}
        position_tolerance: 0.1
        max_acceleration: 0.5
      left_s1:
        pid: {p: 5.0, i: 1.0, d: 1.0}
        position_tolerance: 0.1
        max_acceleration: 0.5
      left_e0:
        pid: {p: 5.0, i: 1.0, d: 1.0}
        position_tolerance: 0.1
        max_acceleration: 0.5
      left_e1:
        pid: {p: 5.0, i: 1.0, d: 1.0}
        position_tolerance: 0.1
        max_acceleration: 0.5
      left_w0:
        pid: {p: 5.0, i: 1.0, d: 1.0}
        position_tolerance: 0.1
        max_acceleration: 0.5
      left_w1:
        pid: {p: 5.0, i: 1.0, d: 1.0}
        position_tolerance: 0.1
        max_acceleration: 0.5
      left_w2:
        pid: {p: 10.0, i: 0.0, d: 0.0}
        position_tolerance: 0.1
        max_acceleration: 0.5      
  right_gripper_position_controller:
    type: baxter_controllers/BaxterGripperController
    joint: right_gripper_l_finger_joint
    pid: {p: 1.0, i: 1.0, d: 1.0}