baxter:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  joint_positions_controller:
    type: baxter_controllers/JointPositionsController
    joints:
      right_s0_controller:
        joint: right_s0
        pid: {p: 200.0, i: 0.01, d: 0.1}
      right_s1_controller:
        joint: right_s1
        pid: {p: 800.0, i: 0.01, d: 0.1}
      right_e0_controller:
        joint: right_e0
        pid: {p: 300.0, i: 0.01, d: 0.1}
      right_e1_controller:
        joint: right_e1
        pid: {p: 500.0, i: 0.01, d: 0.1}
      right_w0_controller:
        joint: right_w0
        pid: {p: 200.0, i: 0.01, d: 0.1}
      right_w1_controller:
        joint: right_w1
        pid: {p: 100.0, i: 0.01, d: 0.1}
      right_w2_controller:
        joint: right_w2
        pid: {p: 100.0, i: 0.01, d: 0.1}
      left_s0_controller:
        joint: left_s0
        pid: {p: 200.0, i: 0.01, d: 5.0}
      left_s1_controller:
        joint: left_s1
        pid: {p: 800.0, i: 0.01, d: 10.0}
      left_e0_controller:
        joint: left_e0
        pid: {p: 300.0, i: 0.01, d: 0.1}
      left_e1_controller:
        joint: left_e1
        pid: {p: 500.0, i: 0.01, d: 0.1}
      left_w0_controller:
        joint: left_w0
        pid: {p: 200.0, i: 0.01, d: 0.1}
      left_w1_controller:
        joint: left_w1
        pid: {p: 100.0, i: 0.01, d: 0.1}
      left_w2_controller:
        joint: left_w2
        pid: {p: 100.0, i: 0.01, d: 0.1}
  right_gripper_position_controller:
    type: baxter_controllers/BaxterGripperController
    joint: right_gripper_l_finger_joint
    pid: {p: 1.0, i: 1.0, d: 1.0}