  # Publish all joint states -----------------------------------

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Hardware - Right and Left Joint Position Trajectory Controller -------------------
  left_joint_trajectory_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - left_s0
      - left_s1
      - left_e0
      - left_e1
      - left_w0
      - left_w1
      - left_w2

    constraints:
      goal_time: 3.0                   # Defaults to zero
      stopped_velocity_tolerance: 0.03 # Defaults to 0.01
      left_s0:
        trajectory: 0 
        goal: 0.02       
      left_s1:
        trajectory: 0 
        goal: 0.02       
      left_e0:
        trajectory: 0 
        goal: 0.02       
      left_e1:
        trajectory: 0 
        goal: 0.02       
      left_w0:
        trajectory: 0 
        goal: 0.02       
      left_w1:
        trajectory: 0 
        goal: 0.02       
      left_w2:
        trajectory: 0 
        goal: 0.02       

    state_publish_rate:  50 # Defaults to 50
    action_monitor_rate: 20 # Defaults to 20
    #hold_trajectory_duration: 0 # Defaults to 0.5

  right_joint_trajectory_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - right_s0
      - right_s1
      - right_e0
      - right_e1
      - right_w0
      - right_w1
      - right_w2

    constraints:
      goal_time: 3.0                   
      stopped_velocity_tolerance: 0.03 
      right_s0:
        trajectory: 0 
        goal: 0.02       
      right_s1:
        trajectory: 0 
        goal: 0.02       
      right_e0:
        trajectory: 0 
        goal: 0.02       
      right_e1:
        trajectory: 0 
        goal: 0.02       
      right_w0:
        trajectory: 0 
        goal: 0.02       
      right_w1:
        trajectory: 0 
        goal: 0.02       
      right_w2:
        trajectory: 0 
        goal: 0.02       

    state_publish_rate:  50 # Defaults to 50
    action_monitor_rate: 20 # Defaults to 20
    #hold_trajectory_duration: 0 # Defaults to 0.5

