rethink_rsdk_joint_trajectory_controller:
  constraints:
    goal_time: 0.3
    r_shoulder_pan_joint:
      goal: 0.04
    r_shoulder_lift_joint:
      goal: 0.04
    r_upper_arm_roll_joint:
      goal: 0.04
    r_elbow_flex_joint:
      goal: 0.04
    r_forearm_roll_joint:
      goal: 0.04
    r_wrist_flex_joint:
      goal: 0.04
    r_wrist_roll_joint:
      goal: 0.04